#!/bin/sh

CORAL_ROOT=`dirname $0`
if [ "$CORAL_ROOT" = "" ]
then
	CORAL=`which coral`
	CORAL_ROOT=`dirname $CORAL`
fi

if [ `uname` = "Darwin" ]
then
	export DYLD_LIBRARY_PATH=$CORAL_ROOT/lib:$DYLD_LIBRARY_PATH
else
	export LD_LIBRARY_PATH=$CORAL_ROOT/lib:$LD_LIBRARY_PATH
fi

export CORAL_PATH=$CORAL_ROOT/modules:$CORAL_PATH

$CORAL_ROOT/bin/launcher $@
