#line 2 "scanner.cc"
#line 3 "CSL.l"
#include "parser.hh"

#define YYSTYPE co::csl::Parser::semantic_type

#define YY_NO_INPUT

#ifndef YY_NO_UNISTD_H
#define YY_NO_UNISTD_H 1
#endif



#line 16 "scanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE csl_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via csl_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void csl_restart (FILE *input_file ,yyscan_t yyscanner );
void csl__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE csl__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void csl__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void csl__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void csl_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void csl_pop_buffer_state (yyscan_t yyscanner );

static void csl_ensure_buffer_stack (yyscan_t yyscanner );
static void csl__load_buffer_state (yyscan_t yyscanner );
static void csl__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER csl__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE csl__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE csl__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE csl__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *csl_alloc (yy_size_t ,yyscan_t yyscanner );
void *csl_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void csl_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer csl__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        csl_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            csl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        csl_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            csl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define csl_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[247] =
    {   0,
        0,    0,   55,   55,   60,   60,    0,    0,   85,   83,
       81,   82,   83,   66,   25,   26,   30,   28,   20,   29,
       83,   31,   49,   49,   19,   83,   27,   83,   45,   23,
       24,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   21,   22,   55,   57,
       56,   60,   64,   61,   79,   68,   67,   80,   81,   82,
       51,   54,    0,   52,   49,    0,    0,    0,   47,    0,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
        7,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       55,   56,   56,   58,   60,   61,   62,   61,   79,   77,

       78,   69,   70,   71,   72,   73,   74,   75,   76,    0,
        0,   53,   51,    0,    0,   50,   48,    0,    0,   47,
       46,   32,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   11,   45,   45,   45,   45,   45,
       45,   45,   45,   62,   63,   69,    0,   51,    0,    0,
       52,   59,   47,   46,   33,   45,   45,    2,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   39,   45,   45,
       45,   45,   45,   45,   45,   45,   17,   45,   18,   63,
       65,    0,   51,   47,   45,   45,   45,   45,    5,   35,
       45,    8,   36,   37,   38,   45,   45,   45,   45,   45,

       45,   45,   45,   45,   45,   45,   44,   45,   34,   45,
       45,    6,   45,   45,   45,   13,   45,   45,   40,   16,
       41,   42,   43,   45,   45,    4,   45,    0,   45,   45,
       45,   45,   45,   45,    0,   12,   14,   15,    1,    3,
        9,    0,    0,    0,   10,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   19,   21,   19,    1,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   29,
       31,   32,   33,    1,   29,    1,   34,   35,   36,   37,

       38,   39,   40,   29,   41,   29,   29,   42,   43,   44,
       45,   46,   29,   47,   48,   49,   50,   51,   29,   52,
       53,   29,   54,    1,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[274] =
    {   0,
        0,    0,   53,   54,   55,   56,   61,   62,  707, 1540,
      704, 1540,  702, 1540, 1540, 1540, 1540, 1540, 1540, 1540,
       54,   68,   67,   68, 1540,  660, 1540,    0,  662, 1540,
     1540,   65,   66,   70,   71,   73,   76,   78,   74,   51,
       77,   92,   87,   88,   72,   95, 1540, 1540,    0, 1540,
      115,    0, 1540,   51,    0, 1540, 1540,  138,  671, 1540,
       74, 1540,  669,   99,    0,  120,    0,  657,  653,    0,
      652,   91,  102,  120,  121,  126,  130,  122,  133,  134,
      139,  137,  148,  136,  127,  131,  149,  150,  157,  158,
        0,  182,  185, 1540,    0,  166,  654,  174,    0, 1540,

     1540,  197, 1540, 1540, 1540, 1540, 1540, 1540, 1540,  183,
      659, 1540,  181,  194,  206,  214,    0,  652,    0,  648,
      647,  646,  162,  194,  224,  195,  225,  227,  196,  230,
      229,  231,  233,  234,  645,  235,  237,  239,  240,  243,
      244,  245,  246,  647,  630,  281,  289,  297,  251,  305,
      313, 1540,  642,  640,  639,  323,  249,  638,  324,  325,
      254,  326,  327,  328,  257,  256,  255,  637,  329,  330,
      331,  333,  334,  332,  336,  342,  636,  335,  635,  621,
     1540,  343,  368,  632,  353,  354,  341,  379,  630,  629,
      355,  628,  627,  626,  625,  381,  383,  382,  384,  386,

      387,  388,  390,  267,  389,  391,  616,  395,  448,  394,
      396,  444,  400,  268,  398,  443,  399,  402,  442,  441,
      438,  437,  435,  401,  403,  434,  406,  415,  410,  138,
      411,  412,  413,  414,  401,  425,  419,  417,  415,  339,
      337,  256,  241,  240, 1540, 1540,  461,  516,  571,  615,
      641,  683,  736,  791,  846,  901,  956, 1011, 1053, 1091,
     1133, 1163, 1171, 1199, 1226, 1279, 1326, 1339, 1334, 1376,
     1429, 1476, 1486
    } ;

static yyconst flex_int16_t yy_def[274] =
    {   0,
      246,    1,  247,  247,  248,  248,  249,  249,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  250,  250,  246,  246,  246,  251,  252,  246,
      246,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  246,  246,  253,  246,
      254,  255,  246,  256,  257,  246,  246,  258,  246,  246,
      259,  246,  260,  261,   24,  262,  263,  246,  264,  265,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      253,  254,  254,  246,  255,  256,  266,  256,  257,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  267,
      260,  246,  261,  268,  246,  246,  263,  246,  269,  264,
      270,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  266,  271,  246,  246,  246,  272,  246,
      246,  246,  273,  270,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  271,
      246,  246,  246,  273,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  246,  252,  252,
      252,  252,  252,  252,  246,  252,  252,  252,  252,  252,
      252,  246,  246,  246,  246,    0,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246
    } ;

static yyconst flex_int16_t yy_nxt[1596] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   24,   24,   24,   24,   24,
       24,   25,   26,   27,   10,   28,   29,   29,   29,   29,
       30,   10,   31,   32,   33,   34,   35,   36,   37,   29,
       38,   29,   29,   39,   40,   41,   42,   43,   44,   45,
       46,   29,   29,   47,   48,   50,   50,   53,   53,   97,
       51,   51,   70,   56,   56,   57,   57,   61,   61,   61,
       61,   61,   61,   61,   61,   62,   70,   70,   64,   64,
       63,   70,   70,   70,   70,   70,   98,   70,   70,   70,
       54,   54,   58,   58,   66,   66,   67,  246,   70,   70,

       83,  110,   70,   70,   66,   66,   70,   82,   72,   78,
       73,  110,   89,   70,   74,   75,   76,   79,   67,  246,
       80,   81,   93,   84,   77,   85,  114,   94,  115,   86,
      115,   70,   70,   70,   88,   87,  114,   70,   70,   90,
      101,   70,   70,  122,   70,   70,  123,   70,   70,   70,
       70,  102,  102,  102,  102,  102,  102,  102,  102,   70,
       70,   70,  124,  129,  138,  127,  139,  137,   70,   70,
      125,  103,  104,   70,  246,  126,  105,  130,  128,  131,
      136,  106,  246,  132,  107,  134,  108,  133,  109,  246,
      237,  147,   93,  147,  246,  140,  135,   94,  143,  141,

      142,  246,  150,  155,  150,   70,   70,   70,  149,   98,
      146,  146,  146,  146,  146,  146,  146,  146,  149,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,   70,   70,  158,   70,  156,
       70,   70,   70,  161,   70,   70,   70,  165,   70,  166,
       70,   70,  167,  168,   70,   70,   70,   70,  157,  182,
       70,  182,  159,  162,  160,   70,   70,   70,   70,  228,
      169,  194,  195,  163,  170,  173,  193,  174,   70,   70,
      164,  177,  179,  175,  172,  171,  221,  245,  244,  243,
      186,  189,  176,  178,  146,  146,  146,  146,  146,  146,

      146,  146,  148,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,  204,
       70,  205,   70,   70,  206,  207,  183,  183,  183,  183,
      183,  183,  183,  183,   70,   70,   70,  185,  188,  187,
      199,  198,  201,  191,  190,  196,  192,  203,  200,  202,
      197,  183,  183,  183,  183,  183,  183,  183,  183,  210,
       70,  209,   70,   70,   70,   70,  208,   70,   70,   70,

       70,   70,   70,  212,  222,   70,   70,   70,  223,   70,
       70,   70,   70,   70,   70,  211,  228,   70,  215,  213,
      214,   70,   70,   70,   70,   70,   70,  219,   70,  217,
       70,  216,  224,  227,  225,  229,   70,  218,  220,  231,
      230,  234,  242,  226,  232,   70,   70,  233,   70,   70,
      235,  241,   70,   70,   70,   70,  240,  236,  238,   70,
      239,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   65,   70,   65,   65,
       65,   65,   65,   65,   65,   65,   70,   70,   70,   70,
       70,   70,   65,  119,   65,  246,   70,   70,   70,   70,
       70,   70,   65,  119,  181,  246,   70,   70,   70,  119,
      152,  112,  145,   70,  119,  118,   65,   69,   69,   69,
       69,  112,   59,   70,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   71,   68,   71,   71,   71,   71,

       71,   71,   71,   71,   60,   59,  246,  246,  246,   71,
       71,   71,   71,  246,  246,  246,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   91,   91,  246,   91,
       91,   91,   91,  246,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   92,   92,  246,   92,   92,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   95,   95,  246,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,  246,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,

       95,   96,   96,  246,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   99,   99,  246,   99,
      246,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,   99,   99,   99,   99,   99,   99,  246,   99,   99,
       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,

       99,   99,   99,   99,   99,   99,   99,   99,   99,   99,
       99,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,   61,   61,   61,   61,
       61,   61,   61,   61,  246,  246,  246,  246,  246,  246,
       61,  246,  246,  246,  246,  246,  246,  246,  246,  246,
       61,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  113,  113,  113,  113,
      113,  113,  113,  113,  246,  246,  246,  246,  246,  246,
      113,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      113,  116,  246,  116,  246,  246,  116,  116,  116,  116,
      116,  116,  116,  116,  117,  117,  117,  117,  117,  117,
      117,  117,  246,  246,  246,  246,  246,  117,  117,  246,

      246,  246,  246,  246,  117,  117,  117,  117,  117,  117,
      120,  246,  120,  120,  120,  120,  120,  120,  120,  120,
      246,  246,  246,  246,  246,  120,  120,  120,  120,  246,
      246,  246,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  121,  121,  121,  121,  246,  246,  246,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  144,
      144,  246,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  148,  246,  148,  246,  246,  148,
      148,  148,  148,  148,  148,  148,  148,  151,  246,  151,
      246,  246,  151,  151,  151,  151,  151,  151,  151,  151,
      153,  153,  153,  153,  246,  246,  246,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  154,  246,  154,
      154,  154,  154,  154,  154,  154,  154,  246,  246,  246,

      246,  246,  154,  154,  154,  154,  246,  246,  246,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  180,
      180,  246,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  183,  246,  183,  246,  246,  183,
      183,  183,  183,  183,  183,  183,  183,  184,  246,  184,

      184,  184,  184,  184,  184,  184,  184,  246,  246,  246,
      246,  246,  184,  184,  184,  184,  246,  246,  246,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,    9,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246

    } ;

static yyconst flex_int16_t yy_chk[1596] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,   54,
        3,    4,   40,    7,    8,    7,    8,   21,   21,   21,
       21,   21,   21,   21,   21,   22,   32,   33,   23,   24,
       22,   34,   35,   45,   36,   39,   54,   37,   41,   38,
        5,    6,    7,    8,   23,   24,   23,   24,   43,   44,

       40,   61,   72,   42,   23,   24,   46,   39,   32,   37,
       33,   61,   45,   73,   34,   35,   36,   37,   23,   24,
       38,   38,   51,   41,   36,   42,   64,   51,   66,   42,
       66,   74,   75,   78,   44,   43,   64,   76,   85,   46,
       58,   77,   86,   72,   79,   80,   73,   84,   82,  230,
       81,   58,   58,   58,   58,   58,   58,   58,   58,   83,
       87,   88,   74,   78,   86,   77,   86,   85,   89,   90,
       75,   58,   58,  123,   96,   76,   58,   79,   77,   80,
       84,   58,   98,   81,   58,   82,   58,   81,   58,   92,
      230,  110,   93,  110,   92,   87,   83,   93,   90,   88,

       89,   96,  114,  123,  114,  124,  126,  129,  113,   98,
      102,  102,  102,  102,  102,  102,  102,  102,  113,  115,
      115,  115,  115,  115,  115,  115,  115,  116,  116,  116,
      116,  116,  116,  116,  116,  125,  127,  126,  128,  124,
      131,  130,  132,  129,  133,  134,  136,  133,  137,  133,
      138,  139,  133,  133,  140,  141,  142,  143,  125,  149,
      157,  149,  127,  130,  128,  161,  167,  166,  165,  214,
      133,  166,  167,  131,  134,  138,  165,  139,  204,  214,
      132,  141,  143,  140,  137,  136,  204,  244,  243,  242,
      157,  161,  140,  142,  146,  146,  146,  146,  146,  146,

      146,  146,  147,  147,  147,  147,  147,  147,  147,  147,
      148,  148,  148,  148,  148,  148,  148,  148,  150,  150,
      150,  150,  150,  150,  150,  150,  151,  151,  151,  151,
      151,  151,  151,  151,  156,  159,  160,  162,  163,  164,
      169,  170,  171,  174,  172,  173,  178,  175,  241,  178,
      240,  178,  187,  176,  178,  178,  182,  182,  182,  182,
      182,  182,  182,  182,  185,  186,  191,  156,  160,  159,
      172,  171,  174,  163,  162,  169,  164,  176,  173,  175,
      170,  183,  183,  183,  183,  183,  183,  183,  183,  187,
      188,  186,  196,  198,  197,  199,  185,  200,  201,  202,

      205,  203,  206,  191,  205,  210,  208,  211,  206,  215,
      217,  213,  224,  218,  225,  188,  228,  227,  198,  196,
      197,  229,  231,  232,  233,  234,  239,  202,  238,  200,
      237,  199,  208,  213,  210,  215,  236,  201,  203,  218,
      217,  227,  235,  211,  224,  226,  223,  225,  222,  221,
      228,  234,  220,  219,  216,  212,  233,  229,  231,  209,
      232,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,

      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  250,  207,  250,  250,
      250,  250,  250,  250,  250,  250,  195,  194,  193,  192,
      190,  189,  250,  184,  250,  180,  179,  177,  168,  158,
      155,  154,  250,  153,  145,  144,  135,  122,  121,  120,
      118,  111,   97,   71,   69,   68,  250,  251,  251,  251,
      251,   63,   59,   29,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  252,   26,  252,  252,  252,  252,

      252,  252,  252,  252,   13,   11,    9,    0,    0,  252,
      252,  252,  252,    0,    0,    0,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  253,  253,    0,  253,
      253,  253,  253,    0,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      253,  254,  254,    0,  254,  254,  254,  254,  254,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  255,  255,    0,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,    0,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,

      255,  256,  256,    0,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  257,  257,    0,  257,
        0,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  257,  257,  257,  257,  257,    0,  257,  257,
      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,

      257,  257,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  259,  259,  259,  259,
      259,  259,  259,  259,    0,    0,    0,    0,    0,    0,
      259,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      259,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  261,  261,  261,  261,
      261,  261,  261,  261,    0,    0,    0,    0,    0,    0,
      261,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      261,  262,    0,  262,    0,    0,  262,  262,  262,  262,
      262,  262,  262,  262,  263,  263,  263,  263,  263,  263,
      263,  263,    0,    0,    0,    0,    0,  263,  263,    0,

        0,    0,    0,    0,  263,  263,  263,  263,  263,  263,
      264,    0,  264,  264,  264,  264,  264,  264,  264,  264,
        0,    0,    0,    0,    0,  264,  264,  264,  264,    0,
        0,    0,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  265,  265,  265,  265,    0,    0,    0,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  266,
      266,    0,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  267,    0,  267,    0,    0,  267,
      267,  267,  267,  267,  267,  267,  267,  268,    0,  268,
        0,    0,  268,  268,  268,  268,  268,  268,  268,  268,
      269,  269,  269,  269,    0,    0,    0,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  270,    0,  270,
      270,  270,  270,  270,  270,  270,  270,    0,    0,    0,

        0,    0,  270,  270,  270,  270,    0,    0,    0,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  271,
      271,    0,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  272,    0,  272,    0,    0,  272,
      272,  272,  272,  272,  272,  272,  272,  273,    0,  273,

      273,  273,  273,  273,  273,  273,  273,    0,    0,    0,
        0,    0,  273,  273,  273,  273,    0,    0,    0,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246

    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "CSL.l"
/* Scanner for the Coral Specification Language (CSL) */

#line 14 "CSL.l"

#include "Loader.h"
#include <co/Exception.h>
#include <cmath>
#include <cstdio>
#include <iomanip>

#define yyterminate() return TK::END
#define YY_USER_ACTION	yylloc->columns( yyleng );

#define SET_BOOL( arg )		(yylval)->b = arg;
#define SET_NUMBER( arg )	(yylval)->num = arg;
#define SET_CSTR( arg )		(yylval)->cstr = arg;
#define SET_STRING( arg )	(yylval)->str = loader.newString( arg );
#define STR_NEW()			(yylval)->str = str = loader.newString();
#define STR_APPEND( aStr )	{ assert( str ); str->append( aStr ); }
#define STR_PUSH( aChr )	{ assert( str ); str->push_back( aChr ); }

#define LEX_ERROR( msg )	{ PUSH_ERROR( *yylloc, msg ); yyterminate(); }

typedef co::csl::Parser::token TK;

/* %option debug */

#line 900 "scanner.cc"

#define INITIAL 0
#define CMT 1
#define CPP 2
#define STR 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int csl_lex_init (yyscan_t* scanner);

int csl_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int csl_lex_destroy (yyscan_t yyscanner );

int csl_get_debug (yyscan_t yyscanner );

void csl_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE csl_get_extra (yyscan_t yyscanner );

void csl_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *csl_get_in (yyscan_t yyscanner );

void csl_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *csl_get_out (yyscan_t yyscanner );

void csl_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t csl_get_leng (yyscan_t yyscanner );

char *csl_get_text (yyscan_t yyscanner );

int csl_get_lineno (yyscan_t yyscanner );

void csl_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * csl_get_lval (yyscan_t yyscanner );

void csl_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *csl_get_lloc (yyscan_t yyscanner );
    
        void csl_set_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int csl_wrap (yyscan_t yyscanner );
#else
extern int csl_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int csl_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int csl_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 53 "CSL.l"



	// mark the current location as the start of the next token
	yylloc_param->step();

	int caller = 0;
	std::string* str = NULL;


#line 1153 "scanner.cc"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			csl_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				csl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		csl__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 246 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "CSL.l"
return TK::COMPONENT;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "CSL.l"
return TK::ENUM;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "CSL.l"
return TK::EXCEPTION;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "CSL.l"
return TK::EXTENDS;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "CSL.l"
SET_BOOL( false ) return TK::BOOLEAN;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "CSL.l"
return TK::IMPORT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "CSL.l"
return TK::IN;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "CSL.l"
return TK::INOUT;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "CSL.l"
return TK::INTERFACE;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "CSL.l"
return TK::NATIVECLASS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "CSL.l"
return TK::OUT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "CSL.l"
return TK::PROVIDES;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "CSL.l"
return TK::RAISES;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "CSL.l"
return TK::READONLY;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "CSL.l"
return TK::RECEIVES;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "CSL.l"
return TK::STRUCT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "CSL.l"
SET_BOOL( true ) return TK::BOOLEAN;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "CSL.l"
return TK::VOID;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "CSL.l"
return ';';
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "CSL.l"
return ',';
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "CSL.l"
return '{';
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "CSL.l"
return '}';
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "CSL.l"
return '[';
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "CSL.l"
return ']';
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "CSL.l"
return '(';
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "CSL.l"
return ')';
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "CSL.l"
return '=';
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "CSL.l"
return '+';
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "CSL.l"
return '-';
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "CSL.l"
return '*';
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "CSL.l"
return '/';
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "CSL.l"
SET_CSTR( "any" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 96 "CSL.l"
SET_CSTR( "bool" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "CSL.l"
SET_CSTR( "double" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 98 "CSL.l"
SET_CSTR( "float" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 99 "CSL.l"
SET_CSTR( "int16" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 100 "CSL.l"
SET_CSTR( "int32" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "CSL.l"
SET_CSTR( "int64" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 102 "CSL.l"
SET_CSTR( "int8" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 103 "CSL.l"
SET_CSTR( "string" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 104 "CSL.l"
SET_CSTR( "uint16" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 105 "CSL.l"
SET_CSTR( "uint32" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 106 "CSL.l"
SET_CSTR( "uint64" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 107 "CSL.l"
SET_CSTR( "uint8" ) return TK::PRIMITIVE_TYPE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "CSL.l"
SET_STRING( yytext ) return TK::ID;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "CSL.l"
SET_STRING( yytext ) return TK::QUALIFIED_ID;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "CSL.l"
SET_STRING( yytext + 1 ) return TK::ANNOTATION_ID;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "CSL.l"
SET_NUMBER( strtol( &yytext[2], NULL, 16 ) ) return TK::NUMBER;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "CSL.l"
SET_NUMBER( strtol( yytext, NULL, 10 ) ) return TK::NUMBER;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "CSL.l"
SET_NUMBER( strtod( yytext, NULL ) ) return TK::NUMBER;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "CSL.l"
SET_NUMBER( strtod( yytext, NULL ) ) return TK::NUMBER;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "CSL.l"
SET_NUMBER( strtod( yytext, NULL ) ) return TK::NUMBER;
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 119 "CSL.l"
{	// single-line comments
						yylloc->lines( 1 );
						if( loader.hasDoc() )
						{
							yytext[yyleng - 1] = '\0';
							SET_STRING( &yytext[2] )
							return TK::COMMENT;
						}
						yylloc->step();
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "CSL.l"
{	// start of a multi-line comment
						if( loader.hasDoc() ) STR_NEW()
						caller = YY_START; BEGIN(CMT);
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "CSL.l"
{	// eat anything that's not an '*'
						if( loader.hasDoc() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 138 "CSL.l"
{	// eat up '*'s not followed by '/'s
						if( loader.hasDoc() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 141 "CSL.l"
{	// eat up newlines
						if( loader.hasDoc() ) STR_PUSH( '\n' )
						yylloc->lines( 1 );
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 145 "CSL.l"
{	// end of the multi-line comment
						BEGIN(caller); if( loader.hasDoc() ) return TK::COMMENT;
					}
	YY_BREAK
case YY_STATE_EOF(CMT):
#line 148 "CSL.l"
LEX_ERROR( "unclosed comment" );
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 151 "CSL.l"
{	// start of a C++ code block
						if( loader.hasCppBlocks() ) STR_NEW()
						caller = YY_START; BEGIN(CPP);
					}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 155 "CSL.l"
{	// eat anything that's not a 'c'
						if( loader.hasCppBlocks() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 158 "CSL.l"
{	// eat up 'c's not followed by '+'s
						if( loader.hasCppBlocks() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "CSL.l"
{	// eat up 'c+'s not followed by '>'s
						if( loader.hasCppBlocks() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 164 "CSL.l"
{	// eat up 'c++'s not followed by '>'s
						if( loader.hasCppBlocks() ) STR_APPEND( yytext )
					}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 167 "CSL.l"
{	// eat up newlines
						if( loader.hasCppBlocks() ) STR_PUSH( '\n' )
						yylloc->lines( 1 );
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 171 "CSL.l"
{	// end of the C++ code block
						BEGIN(caller); if( loader.hasCppBlocks() ) return TK::CPP_BLOCK;
					}
	YY_BREAK
case YY_STATE_EOF(CPP):
#line 174 "CSL.l"
LEX_ERROR( "unclosed C++ block" );
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 177 "CSL.l"
/* string literal */ STR_NEW() caller = YY_START; BEGIN(STR);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 178 "CSL.l"
BEGIN(caller); return TK::LITERAL;
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 179 "CSL.l"
LEX_ERROR( "unterminated string literal" );
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 180 "CSL.l"
{	/* decimal escape sequence */
						long value = strtol( yytext + 1, NULL, 10 );
						if( value > 0xFF )
							LEX_ERROR( "decimal escape sequence is out of range (0-255)" );
						STR_PUSH( static_cast<char>( value ) );
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 186 "CSL.l"
STR_PUSH( '\a' )
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 187 "CSL.l"
STR_PUSH( '\b' )
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 188 "CSL.l"
STR_PUSH( '\f' )
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 189 "CSL.l"
STR_PUSH( '\n' )
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 190 "CSL.l"
STR_PUSH( '\r' )
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 191 "CSL.l"
STR_PUSH( '\t' )
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 192 "CSL.l"
STR_PUSH( '\v' )
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 193 "CSL.l"
STR_PUSH( yytext[1] )
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 194 "CSL.l"
yylloc->lines( 1 );
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 195 "CSL.l"
STR_APPEND( yytext )
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 196 "CSL.l"
LEX_ERROR( "incomplete escape sequence" );
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 199 "CSL.l"
/* eat blanks */ yylloc->step();
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 200 "CSL.l"
yylloc->lines( 1 ); yylloc->step();
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 201 "CSL.l"
{
					LEX_ERROR( "unknown character '" << yytext[0] << "' (0x"
						<< std::hex << static_cast<int>( yytext[0] ) << ")" );
				}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 206 "CSL.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1713 "scanner.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * csl_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( csl_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of csl_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					csl_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			csl_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) csl_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 246);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					csl_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( csl_wrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void csl_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        csl_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            csl__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	csl__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	csl__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void csl__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		csl_pop_buffer_state();
	 *		csl_push_buffer_state(new_buffer);
     */
	csl_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	csl__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (csl_wrap()) processing, but the only time this flag
	 * is looked at is after csl_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void csl__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE csl__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) csl_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in csl__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) csl_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in csl__create_buffer()" );

	b->yy_is_our_buffer = 1;

	csl__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with csl__create_buffer()
 * @param yyscanner The scanner object.
 */
    void csl__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		csl_free((void *) b->yy_ch_buf ,yyscanner );

	csl_free((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a csl_restart() or at EOF.
 */
    static void csl__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	csl__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then csl__init_buffer was _probably_
     * called from csl_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void csl__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		csl__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void csl_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	csl_ensure_buffer_stack(yyscanner);

	/* This block is copied from csl__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from csl__switch_to_buffer. */
	csl__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void csl_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	csl__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		csl__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void csl_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)csl_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in csl_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)csl_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in csl_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE csl__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) csl_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in csl__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	csl__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to csl_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       csl__scan_bytes() instead.
 */
YY_BUFFER_STATE csl__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return csl__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to csl_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE csl__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) csl_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in csl__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = csl__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in csl__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE csl_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int csl_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int csl_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *csl_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *csl_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t csl_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *csl_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void csl_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void csl_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "csl_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void csl_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "csl_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see csl__switch_to_buffer
 */
void csl_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void csl_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int csl_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void csl_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * csl_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void csl_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *csl_get_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void csl_set_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* csl_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int csl_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) csl_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* csl_lex_init_extra has the same functionality as csl_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to csl_alloc in
 * the yyextra field.
 */

int csl_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    csl_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) csl_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    csl_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from csl_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * csl_lex_init()
     */
    return 0;
}

/* csl_lex_destroy is for both reentrant and non-reentrant scanners. */
int csl_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		csl__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		csl_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	csl_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        csl_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * csl_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    csl_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *csl_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *csl_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void csl_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see csl_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 206 "CSL.l"



