/*
 * Coral - A lightweight C++ component framework
 * See Copyright Notice in Coral.h
 */

#ifndef _MODULEPARTLOADER_H_
#define _MODULEPARTLOADER_H_

#include "ModulePartLoaderComponent_Base.h"

namespace co {

// forward declarations:
class Library;
class Namespace;
struct TypeDependency;
struct BootstrapFunctions;

/*!
	Default implementation of co.ModulePartLoader, which dynamically loads
	libraries built from code generated by the Coral Compiler.
 */
class ModulePartLoaderComponent : public ModulePartLoaderComponent_Base
{
public:
	ModulePartLoaderComponent();
	virtual ~ModulePartLoaderComponent();

	// ModulePartLoader methods:
	bool canLoadModulePart( const std::string& moduleName );
	ModulePart* loadModulePart( const std::string& moduleName );

private:
	bool locateModuleLibrary( const std::string& moduleName, std::string* filename = 0 );
	void resolveModuleFunctions( Library* lib, BootstrapFunctions& bf );
	bool checkVerificationData( const std::string& data );
	void checkTypeDependencies( const TypeDependency* td );
};

} // namespace co

#endif
