/*
 * Coral - A C++ Component Framework.
 * See Copyright Notice in Coral.h
 */

#ifndef _MODULEPARTLOADER_H_
#define _MODULEPARTLOADER_H_

#include "ModulePartLoaderComponent_Base.h"

// forward declarations:
struct TypeDependency;
struct BootstrapFunctions;
namespace co {
	class Library;
	class Namespace;
} // namespace co

/*!
	Default implementation of co.ModulePartLoader, which dynamically loads
	libraries built from code generated by the Coral Compiler.
 */
class ModulePartLoader : public co::ModulePartLoaderComponent_Base
{
public:
	ModulePartLoader();
	virtual ~ModulePartLoader();

	// co::ModulePartLoader methods:
	bool canLoadModulePart( const std::string& moduleName );
	co::ModulePart* loadModulePart( const std::string& moduleName );

private:
	bool locateModuleLibrary( const std::string& moduleName, std::string* filename = 0 );
	void resolveModuleFunctions( co::Library* lib, BootstrapFunctions& bf );
	bool checkVerificationData( const std::string& data );
	void checkTypeDependencies( const TypeDependency* td );
};

#endif
