class {{TYPE_NAME}} : {{#SUPERTYPE_LIST}}public {{SUPERTYPE}}{{#SUPERTYPE_LIST_separator}}, {{/SUPERTYPE_LIST_separator}}{{/SUPERTYPE_LIST}}
{
public:
	virtual ~{{TYPE_NAME}}() {;}

	{{>CPP_BLOCK}}

{{#ATTRIBUTE_LIST}}
{{#GETTER}}
{{NEWLINE}}
	virtual {{RETURN_TYPE}} {{METHOD_NAME}}() = 0;
{{/GETTER}}
{{#SETTER}}
{{NEWLINE}}
	virtual void {{METHOD_NAME}}( {{PARAMETER_TYPE}} {{PARAMETER_NAME}} ) = 0;
{{/SETTER}}
{{/ATTRIBUTE_LIST}}

{{#METHOD_LIST}}
{{NEWLINE}}
	virtual {{RETURN_TYPE}} {{METHOD_NAME}}({{#HAS_PARAMETERS_TRUE}} {{#PARAMETER_LIST}}{{PARAMETER_TYPE}} {{PARAMETER_NAME}}{{#PARAMETER_LIST_separator}}, {{/PARAMETER_LIST_separator}}{{/PARAMETER_LIST}} {{/HAS_PARAMETERS_TRUE}}) = 0;
{{/METHOD_LIST}}

{{#HAS_AMBIGUOUS_BASES}}
{{NEWLINE}}
	CORAL_DISAMBIGUATE_CO_INTERFACE( {{FIRST_SUPERTYPE}} );
{{/HAS_AMBIGUOUS_BASES}}
};
